export const RECEIVE_NEW_CONVERSATION: 'RECEIVE_NEW_CONVERSATION' = 'RECEIVE_NEW_CONVERSATION';
export const RECEIVE_CONVERSATIONS: 'RECEIVE_CONVERSATIONS' = 'RECEIVE_CONVERSATIONS';
export const RECEIVE_CONVERSATION: 'RECEIVE_CONVERSATION' = 'RECEIVE_CONVERSATION';
export const REMOVE_CREATED_CONVO: 'REMOVE_CREATED_CONVO' = 'REMOVE_CREATED_CONVO';