export const RECEIVE_CHANNELS: 'RECEIVE_CHANNELS' = 'RECEIVE_CHANNELS';
export const RECEIVE_CHANNEL: 'RECEIVE_CHANNEL' = 'RECEIVE_CHANNEL';
export const REMOVE_CHANNEL: 'REMOVE_CHANNEL' = 'REMOVE_CHANNEL';
export const RECEIVE_CREATED_CHANNEL: 'RECEIVE_CREATED_CHANNEL' = 'RECEIVE_CREATED_CHANNEL';
export const RECEIVE_UPDATED_CHANNEL: 'RECEIVE_UPDATED_CHANNEL' = 'RECEIVE_UPDATED_CHANNEL';