export const RECEIVE_INVITATIONS: 'RECEIVE_INVITATIONS' = 'RECEIVE_INVITATIONS';
export const RECEIVE_INVITATION: 'RECEIVE_INVITATION' = 'RECEIVE_INVITATION';
export const REMOVE_INVITATION: 'REMOVE_INVITATION' = 'REMOVE_INVITATION';
export const SOCKET_INVITATION: 'SOCKET_INVITATION' = 'SOCKET_INVITATION';
export type INVITATION_ACTION_TYPES = (
  typeof RECEIVE_INVITATIONS |
  typeof RECEIVE_INVITATION |
  typeof REMOVE_INVITATION |
  typeof SOCKET_INVITATION
);