export const RECEIVE_MEMBERSHIPS: 'RECEIVE_MEMBERSHIPS' = 'RECEIVE_MEMBERSHIPS';
export const RECEIVE_MEMBERSHIP: 'RECEIVE_MEMBERSHIP' = 'RECEIVE_MEMBERSHIP';
export const REMOVE_MEMBERSHIP: 'REMOVE_MEMBERSHIP' = 'REMOVE_MEMBERSHIP';
export const RECEIVE_NICKNAME: 'RECEIVE_NICKNAME' = 'RECEIVE_NICKNAME';
export type MEMBERSHIP_ACTION_TYPES = (
  typeof RECEIVE_MEMBERSHIPS |
  typeof RECEIVE_MEMBERSHIP |
  typeof REMOVE_MEMBERSHIP |
  typeof RECEIVE_NICKNAME
);