export const RECEIVE_SERVERS: 'RECEIVE_SERVERS' = 'RECEIVE_SERVERS';
export const RECEIVE_SERVER: 'RECEIVE_SERVER' = 'RECEIVE_SERVER';
export const RECEIVE_SERVER_ERRORS: 'RECEIVE_SERVER_ERRORS' = 'RECEIVE_SERVER_ERRORS';
export const REMOVE_SERVER_ERRORS: 'REMOVE_SERVER_ERRORS' = 'REMOVE_SERVER_ERRORS';
export const REMOVE_SERVER: 'REMOVE_SERVER' = 'REMOVE_SERVER';
export const RECEIVE_INVITED_SERVER: 'RECEIVE_INVITED_SERVER' = 'RECEIVE_INVITED_SERVER';
export const RECEIVE_LOCAL_USERNAME: 'RECEIVE_LOCAL_USERNAME' = 'RECEIVE_LOCAL_USERNAME';
export const RECEIVE_NEW_SERVER: 'RECEIVE_NEW_SERVER' = 'RECEIVE_NEW_SERVER';
export const RECEIVE_JOINED_SERVER: 'RECEIVE_JOINED_SERVER' = 'RECEIVE_JOINED_SERVER';
export const LEAVE_SERVER: 'LEAVE_SERVER' = 'LEAVE_SERVER';
export const RECEIVE_SERVER_INFO: 'RECEIVE_SERVER_INFO' = 'RECEIVE_SERVER_INFO';
export const KICK_MEMBER: 'KICK_MEMBER' = 'KICK_MEMBER';
export const LOAD_MEMBERS: 'LOAD_MEMBERS' = 'LOAD_MEMBERS';
export type SERVER_ACTION_TYPES = (
  typeof RECEIVE_SERVERS |
  typeof RECEIVE_SERVER |
  typeof RECEIVE_SERVER_ERRORS |
  typeof REMOVE_SERVER_ERRORS |
  typeof REMOVE_SERVER |
  typeof RECEIVE_INVITED_SERVER |
  typeof RECEIVE_LOCAL_USERNAME |
  typeof RECEIVE_NEW_SERVER |
  typeof RECEIVE_JOINED_SERVER |
  typeof LEAVE_SERVER |
  typeof RECEIVE_SERVER_INFO |
  typeof KICK_MEMBER |
  typeof LOAD_MEMBERS
);