export const RECEIVE_CURRENT_USER: 'RECEIVE_CURRENT_USER' = 'RECEIVE_CURRENT_USER';
export const LOGOUT_CURRENT_USER: 'LOGOUT_CURRENT_USER' = 'LOGOUT_CURRENT_USER';
export const RECEIVE_SESSION_ERRORS: 'RECEIVE_SESSION_ERRORS' = 'RECEIVE_SESSION_ERRORS';
export const REMOVE_SESSION_ERRORS: 'REMOVE_SESSION_ERRORS' = 'REMOVE_SESSION_ERRORS';
export const RECEIVE_USER_LOAD_DATA: 'RECEIVE_USER_LOAD_DATA' = 'RECEIVE_USER_LOAD_DATA';
export const RECEIVE_PRIVATE_USER_LOAD_DATA: 'RECEIVE_PRIVATE_USER_LOAD_DATA' = 'RECEIVE_PRIVATE_USER_LOAD_DATA';
export type SESSION_ACTION_TYPES = (
  typeof RECEIVE_CURRENT_USER |
  typeof LOGOUT_CURRENT_USER |
  typeof RECEIVE_SESSION_ERRORS |
  typeof REMOVE_SESSION_ERRORS |
  typeof RECEIVE_USER_LOAD_DATA |
  typeof RECEIVE_PRIVATE_USER_LOAD_DATA
);