export const RECEIVE_CHAT_SUB: 'RECEIVE_CHAT_SUB' = 'RECEIVE_CHAT_SUB';
export const RECEIVE_CHAT_SUBS: 'RECEIVE_CHAT_SUBS' = 'RECEIVE_CHAT_SUBS';
export const REMOVE_CHAT_SUBS: 'REMOVE_CHAT_SUBS' = 'REMOVE_CHAT_SUBS';
export const RECEIVE_SERVER_SUB: 'RECEIVE_SERVER_SUB' = 'RECEIVE_SERVER_SUB';
export const REMOVE_SERVER_SUBS: 'REMOVE_SERVER_SUBS' = 'REMOVE_SERVER_SUBS';
export const REMOVE_SERVER_SUB: 'REMOVE_SERVER_SUB' = 'REMOVE_SERVER_SUB';
export const RECEIVE_SESSION_SUB: 'RECEIVE_SESSION_SUB' = 'RECEIVE_SESSION_SUB';
export type SOCKET_ACTION_TYPES = (
  typeof RECEIVE_CHAT_SUB |
  typeof RECEIVE_CHAT_SUBS |
  typeof REMOVE_CHAT_SUBS |
  typeof RECEIVE_SERVER_SUB |
  typeof REMOVE_SERVER_SUBS |
  typeof REMOVE_SERVER_SUB |
  typeof RECEIVE_SESSION_SUB
);