import {
  CHANNEL_ACTION_TYPES,
  CONVERSATION_ACTION_TYPES,
  INVITATION_ACTION_TYPES,
  MEMBERSHIP_ACTION_TYPES,
  MESSAGE_ACTION_TYPES,
  MISC_ACTION_TYPES,
  SERVER_ACTION_TYPES,
  SESSION_ACTION_TYPES,
  SOCKET_ACTION_TYPES,
  UI_ACTION_TYPES,
  USER_ACTION_TYPES,
} from '@constants';

export type Action = {
  type: (
    CHANNEL_ACTION_TYPES |
    CONVERSATION_ACTION_TYPES |
    INVITATION_ACTION_TYPES |
    MEMBERSHIP_ACTION_TYPES |
    MESSAGE_ACTION_TYPES |
    MISC_ACTION_TYPES |
    SERVER_ACTION_TYPES |
    SESSION_ACTION_TYPES |
    SOCKET_ACTION_TYPES |
    UI_ACTION_TYPES |
    USER_ACTION_TYPES
  ),
  payload: {},
}